name: genreg
channels:
  - conda-forge
  - defaults
  - astra-toolbox
  - nvidia
dependencies:
  - python=3.11
  - scikit-image
  - astra-toolbox=2.4.1
  - pip
  - pip:
    - deepinv==0.4.0
    - diffusers==0.38.0
    - lpips==0.1.4
    - matplotlib==3.10.9
    - torch==2.11.0
    - torchvision==0.26.0
    - transformers==5.8.0
    - accelerate==1.13.0
    - gdown